import json

def generate_markdown_report(blueprint_data: dict) -> str:
    meta = blueprint_data.get("meta", {})
    title = meta.get("title", "Startup Blueprint")

    md = f"""# AI STARTUP BUILDER - EXECUTIVE BLUEPRINT
**Project Title:** {title}  
**Idea Description:** {meta.get('idea')}  
**Industry:** {meta.get('industry')} | **Budget:** {meta.get('budget')} | **Target Users:** {meta.get('target_users')}  
**Generated At:** {meta.get('generated_at')}  

---

## 1. Executive Summary & Validation
- **Validation Score:** {blueprint_data.get('idea_analyzer', {}).get('validation_score')}/100
- **Problem Statement:** {blueprint_data.get('idea_analyzer', {}).get('problem_statement')}
- **Solution Overview:** {blueprint_data.get('idea_analyzer', {}).get('solution_overview')}
- **Unique Value Proposition:** {blueprint_data.get('idea_analyzer', {}).get('unique_value_proposition')}

---

## 2. Market Research
- **TAM:** {blueprint_data.get('market_research', {}).get('tam')}
- **SAM:** {blueprint_data.get('market_research', {}).get('sam')}
- **SOM:** {blueprint_data.get('market_research', {}).get('som')}
- **Growth Rate:** {blueprint_data.get('market_research', {}).get('industry_growth_rate')}

---

## 3. Business Model Canvas & Revenue Tiers
- **Revenue Model:** {blueprint_data.get('revenue', {}).get('primary_model')}
- **Projected MRR (Year 1):** {blueprint_data.get('revenue', {}).get('projected_mrr_year1')}
- **Pricing Strategy:** {blueprint_data.get('pricing', {}).get('annual_discount')}

---

## 4. Technical Architecture & Database Schema
```sql
{blueprint_data.get('database_designer', {}).get('sql_schema')}
```

---

## 5. Financial Projections
- **Initial Build Cost:** {blueprint_data.get('finance', {}).get('initial_build_cost')}
- **Monthly Infra:** {blueprint_data.get('finance', {}).get('monthly_server_infra')}
- **ROI (Year 3):** {blueprint_data.get('finance', {}).get('roi_year3')}

---
*Generated by AI STARTUP BUILDER Platform*
"""
    return md

def generate_json_export(blueprint_data: dict) -> str:
    return json.dumps(blueprint_data, indent=2)
