import json
from datetime import datetime

def format_list(items):
    if not items:
        return "N/A"
    return "\n".join([f"- {item}" for item in items])

def format_dict(data):
    if not data:
        return "N/A"
    return "\n".join([f"- **{k.title()}**: {v}" for k, v in data.items()])

def generate_markdown_report(project, startup_analysis, market_research, competitor_analysis, financial_analysis) -> str:
    md = f"""# AI STARTUP BUILDER - EXECUTIVE BLUEPRINT
**Project Title:** {project.name}  
**Idea Description:** {project.description}  
**Industry:** {project.industry}  
**Generated At:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC  

---

## 1. Executive Summary
{startup_analysis.executive_summary if startup_analysis else "N/A"}

### Problem Statement
{startup_analysis.problem_statement if startup_analysis else "N/A"}

### Solution
{startup_analysis.solution if startup_analysis else "N/A"}

### Value Proposition
{startup_analysis.value_proposition if startup_analysis else "N/A"}

---

## 2. Market Research
### TAM, SAM, SOM
{format_dict(market_research.tam_sam_som) if market_research else "N/A"}

### Target Demographics
{format_list(market_research.target_demographics) if market_research else "N/A"}

### Market Trends
{format_list(market_research.market_trends) if market_research else "N/A"}

### SWOT Analysis
{format_dict(market_research.swot_analysis) if market_research else "N/A"}

---

## 3. Competitive Landscape
### Competitive Advantage
{competitor_analysis.competitive_advantage if competitor_analysis else "N/A"}

### Direct Competitors
"""
    if competitor_analysis and competitor_analysis.direct_competitors:
        for comp in competitor_analysis.direct_competitors:
            md += f"- **{comp.get('name', 'Unknown')}**\n"
            md += f"  - Strengths: {comp.get('strengths', 'N/A')}\n"
            md += f"  - Weaknesses: {comp.get('weaknesses', 'N/A')}\n"
    else:
        md += "N/A\n"

    md += """
### Indirect Competitors
"""
    if competitor_analysis and competitor_analysis.indirect_competitors:
        for comp in competitor_analysis.indirect_competitors:
            md += f"- **{comp.get('name', 'Unknown')}** (Overlap: {comp.get('overlap', 'N/A')})\n"
    else:
        md += "N/A\n"

    md += """
---

## 4. Financial Projections
### Revenue Streams
"""
    if financial_analysis and financial_analysis.revenue_streams:
        for stream in financial_analysis.revenue_streams:
            md += f"- **{stream.get('name', 'Unknown')}**: {stream.get('description', '')}\n"
    else:
        md += "N/A\n"
        
    md += """
### Cost Structure
"""
    if financial_analysis and financial_analysis.cost_structure:
        for cost in financial_analysis.cost_structure:
            md += f"- **{cost.get('category', 'Unknown')}**: {cost.get('description', '')}\n"
    else:
        md += "N/A\n"

    md += f"""
### Break-Even Point
{financial_analysis.break_even_point if financial_analysis else "N/A"}

### Funding Requirements
{financial_analysis.funding_requirements if financial_analysis else "N/A"}

---

## 5. Business Model Canvas
"""
    if startup_analysis and startup_analysis.business_model_canvas:
        bmc = startup_analysis.business_model_canvas
        md += f"**Key Partners:**\n{format_list(bmc.get('key_partners'))}\n\n"
        md += f"**Key Activities:**\n{format_list(bmc.get('key_activities'))}\n\n"
        md += f"**Key Resources:**\n{format_list(bmc.get('key_resources'))}\n\n"
        md += f"**Value Propositions:**\n{format_list(bmc.get('value_propositions'))}\n\n"
        md += f"**Customer Relationships:**\n{format_list(bmc.get('customer_relationships'))}\n\n"
        md += f"**Channels:**\n{format_list(bmc.get('channels'))}\n\n"
        md += f"**Customer Segments:**\n{format_list(bmc.get('customer_segments'))}\n\n"
        md += f"**Cost Structure:**\n{format_list(bmc.get('cost_structure'))}\n\n"
        md += f"**Revenue Streams:**\n{format_list(bmc.get('revenue_streams'))}\n\n"
    else:
        md += "N/A\n"

    md += """
---
*Generated by AI STARTUP BUILDER Platform*
"""
    return md
