"""Production schema refactor

Revision ID: 83ef0b92cc32
Revises: d1984f9adfbf
Create Date: 2026-08-02 18:44:16.569116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '83ef0b92cc32'
down_revision: Union[str, Sequence[str], None] = 'd1984f9adfbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)

    op.create_table('roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('user_roles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    op.create_table('ai_conversations',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_project_id'), ['project_id'], unique=False)

    op.create_table('knowledge_documents',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('s3_url', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_project_id'), ['project_id'], unique=False)

    op.create_table('location_analysis',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('demographics', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_analysis_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_analysis_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_analysis_project_id'), ['project_id'], unique=False)

    op.create_table('startup_reports',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('startup_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_startup_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_startup_reports_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_startup_reports_project_id'), ['project_id'], unique=False)

    op.create_table('visualization_history',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('chart_type', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visualization_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visualization_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visualization_history_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_visualization_history_project_id'), ['project_id'], unique=False)

    op.create_table('ai_messages',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_messages_id'), ['id'], unique=False)

    op.create_table('knowledge_chunks',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('chroma_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_chroma_id'), ['chroma_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_id'), ['id'], unique=False)


    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('action', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('entity_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('entity_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('metadata_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_activity_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('activity_logs_project_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('activity_type')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('project_id')
        batch_op.drop_column('description')

    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('metric_value',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_analytics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_metric_name'), ['metric_name'], unique=False)
        batch_op.drop_column('date')

    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('website', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('strengths', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('weaknesses', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_competitors_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitors_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitors_project_id'), ['project_id'], unique=False)
        batch_op.drop_constraint('competitors_location_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.drop_column('location_id')
        batch_op.drop_column('place_id')
        batch_op.drop_column('distance_meters')
        batch_op.drop_column('rating')

    with op.batch_alter_table('market_research', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('insights', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_market_research_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_research_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_research_project_id'), ['project_id'], unique=False)
        batch_op.drop_column('swot_analysis')
        batch_op.drop_column('market_trends')
        batch_op.drop_column('target_demographics')
        batch_op.drop_column('tam_sam_som')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('type')
        batch_op.drop_column('read')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)
        batch_op.drop_column('use_count')
        batch_op.drop_column('idea_description')
        batch_op.drop_column('country')
        batch_op.drop_column('industry')
        batch_op.drop_column('tech_preference')
        batch_op.drop_column('is_archived')
        batch_op.drop_column('favorite')
        batch_op.drop_column('last_active_tab')
        batch_op.drop_column('current_agent')
        batch_op.drop_column('pinned')
        batch_op.drop_column('keywords')
        batch_op.drop_column('progress')
        batch_op.drop_column('target_users')
        batch_op.drop_column('estimated_completion')
        batch_op.drop_column('last_opened')
        batch_op.drop_column('budget')
        batch_op.drop_column('view_count')
        batch_op.drop_column('title')
        batch_op.drop_column('business_type')

    with op.batch_alter_table('shared_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_shared_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_projects_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_projects_user_email'), ['user_email'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_deleted'), ['is_deleted'], unique=False)
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('usage_limit')
        batch_op.drop_column('role')
        batch_op.drop_column('api_key')
        batch_op.drop_column('hashed_password')

    # Level 1 + Level 0 (Children and independent tables)
    op.drop_table('favorite_designs')
    op.drop_table('brand_styles')
    op.drop_table('design_reports')
    op.drop_table('project_chats')
    op.drop_table('location_scores')
    op.drop_table('roi_analysis')
    op.drop_table('heatmaps')
    op.drop_table('business_analysis')
    op.drop_table('traffic')
    op.drop_table('saved_locations')
    
    op.drop_table('reports')
    op.drop_table('favorites')
    op.drop_table('project_versions')
    op.drop_table('blueprints')
    op.drop_table('project_tags')
    
    with op.batch_alter_table('maps_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maps_cache_query'))

    op.drop_table('maps_cache')
    
    op.drop_table('comments')
    op.drop_table('agent_logs')
    
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_identifier'))

    op.drop_table('otp')
    
    op.drop_table('uploaded_files')
    op.drop_table('recent_searches')
    op.drop_table('sessions')
    op.drop_table('startup_analysis')
    op.drop_table('financial_analysis')
    op.drop_table('password_reset')
    op.drop_table('downloads')
    op.drop_table('login_history')
    op.drop_table('guest_users')
    op.drop_table('devices')
    op.drop_table('agent_runs')
    op.drop_table('competitor_analysis')
    op.drop_table('profiles')

    # Level 2 (Intermediate Parents)
    op.drop_table('visualization_images')
    op.drop_table('chat_sessions')

    # Level 3 (Root Parents)

    op.drop_table('visualization_projects')
    op.drop_table('locations')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('api_key', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('usage_limit', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('is_active')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('shared_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_projects_user_email'))
        batch_op.drop_index(batch_op.f('ix_shared_projects_project_id'))
        batch_op.drop_index(batch_op.f('ix_shared_projects_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('view_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('last_opened', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('estimated_completion', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('target_users', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('keywords', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('pinned', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('current_agent', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('last_active_tab', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('favorite', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_archived', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('tech_preference', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('idea_description', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('use_count', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.drop_index(batch_op.f('ix_projects_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_read')

    with op.batch_alter_table('market_research', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tam_sam_som', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('target_demographics', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('market_trends', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('swot_analysis', sqlite.JSON(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_market_research_project_id'))
        batch_op.drop_index(batch_op.f('ix_market_research_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_market_research_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('insights')
        batch_op.drop_column('query')

    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('distance_meters', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('place_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('location_id', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'locations', ['location_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_competitors_project_id'))
        batch_op.drop_index(batch_op.f('ix_competitors_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_competitors_id'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('weaknesses')
        batch_op.drop_column('strengths')
        batch_op.drop_column('website')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_analytics_metric_name'))
        batch_op.drop_index(batch_op.f('ix_analytics_id'))
        batch_op.alter_column('metric_value',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('project_id', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('activity_type', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_activity_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_action'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('metadata_json')
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')
        batch_op.drop_column('action')
        batch_op.drop_column('user_id')

    op.create_table('profiles',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('business_analysis',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('location_id', sa.VARCHAR(), nullable=True),
    sa.Column('advantages', sqlite.JSON(), nullable=True),
    sa.Column('challenges', sqlite.JSON(), nullable=True),
    sa.Column('recommendation', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor_analysis',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('direct_competitors', sqlite.JSON(), nullable=True),
    sa.Column('indirect_competitors', sqlite.JSON(), nullable=True),
    sa.Column('competitive_advantage', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('is_pinned', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heatmaps',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('location_id', sa.VARCHAR(), nullable=True),
    sa.Column('data_points', sqlite.JSON(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('duration_seconds', sa.FLOAT(), nullable=True),
    sa.Column('progress', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_designs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('visualization_image_id', sa.VARCHAR(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visualization_image_id'], ['visualization_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('device_id', sa.VARCHAR(), nullable=False),
    sa.Column('device_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_active', sa.DATETIME(), nullable=True),
    sa.Column('is_trusted', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guest_users',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('device_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('is_converted', sa.BOOLEAN(), nullable=True),
    sa.Column('converted_user_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['converted_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('roi_analysis',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('location_id', sa.VARCHAR(), nullable=True),
    sa.Column('estimated_rent', sa.FLOAT(), nullable=True),
    sa.Column('estimated_revenue', sa.FLOAT(), nullable=True),
    sa.Column('break_even_months', sa.INTEGER(), nullable=True),
    sa.Column('roi_percentage', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_scores',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('location_id', sa.VARCHAR(), nullable=True),
    sa.Column('foot_traffic_score', sa.FLOAT(), nullable=True),
    sa.Column('demographics_score', sa.FLOAT(), nullable=True),
    sa.Column('competition_score', sa.FLOAT(), nullable=True),
    sa.Column('accessibility_score', sa.FLOAT(), nullable=True),
    sa.Column('overall_score', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_history',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('login_time', sa.DATETIME(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('downloads',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('format', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('token', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('financial_analysis',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('revenue_streams', sqlite.JSON(), nullable=True),
    sa.Column('cost_structure', sqlite.JSON(), nullable=True),
    sa.Column('pricing_strategy', sqlite.JSON(), nullable=True),
    sa.Column('break_even_point', sa.VARCHAR(), nullable=True),
    sa.Column('funding_requirements', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('startup_analysis',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('executive_summary', sa.TEXT(), nullable=True),
    sa.Column('problem_statement', sa.TEXT(), nullable=True),
    sa.Column('solution', sa.TEXT(), nullable=True),
    sa.Column('value_proposition', sa.TEXT(), nullable=True),
    sa.Column('business_model_canvas', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(), nullable=False),
    sa.Column('device_info', sa.VARCHAR(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_table('saved_locations',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=True),
    sa.Column('location_id', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_reports',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('visualization_project_id', sa.VARCHAR(), nullable=False),
    sa.Column('design_summary', sa.TEXT(), nullable=True),
    sa.Column('business_theme', sa.VARCHAR(), nullable=True),
    sa.Column('architecture_style', sa.VARCHAR(), nullable=True),
    sa.Column('color_palette', sqlite.JSON(), nullable=True),
    sa.Column('material_suggestions', sqlite.JSON(), nullable=True),
    sa.Column('furniture_suggestions', sqlite.JSON(), nullable=True),
    sa.Column('lighting_suggestions', sqlite.JSON(), nullable=True),
    sa.Column('branding_suggestions', sqlite.JSON(), nullable=True),
    sa.Column('smart_suggestions', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['visualization_project_id'], ['visualization_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_chats',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recent_searches',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('search_type', sa.VARCHAR(), nullable=False),
    sa.Column('query', sa.VARCHAR(), nullable=False),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploaded_files',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=False),
    sa.Column('original_filename', sa.VARCHAR(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(), nullable=False),
    sa.Column('mime_type', sa.VARCHAR(), nullable=False),
    sa.Column('file_size_bytes', sa.INTEGER(), nullable=False),
    sa.Column('upload_status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('identifier', sa.VARCHAR(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('purpose', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_identifier'), ['identifier'], unique=False)

    op.create_table('traffic',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('location_id', sa.VARCHAR(), nullable=True),
    sa.Column('average_daily_vehicles', sa.INTEGER(), nullable=True),
    sa.Column('peak_hours', sqlite.JSON(), nullable=True),
    sa.Column('pedestrian_activity', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_logs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('agent_key', sa.VARCHAR(), nullable=False),
    sa.Column('agent_name', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('execution_time_seconds', sa.FLOAT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=False),
    sa.Column('lat', sa.FLOAT(), nullable=False),
    sa.Column('lng', sa.FLOAT(), nullable=False),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.Column('country', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maps_cache',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('query', sa.VARCHAR(), nullable=True),
    sa.Column('response_data', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maps_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maps_cache_query'), ['query'], unique=False)

    op.create_table('project_tags',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('color', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blueprints',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=False),
    sa.Column('pdf_file', sa.VARCHAR(), nullable=True),
    sa.Column('ppt_file', sa.VARCHAR(), nullable=True),
    sa.Column('docx_file', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('brand_styles',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('visualization_project_id', sa.VARCHAR(), nullable=False),
    sa.Column('store_logo_placement', sa.VARCHAR(), nullable=True),
    sa.Column('sign_board', sa.VARCHAR(), nullable=True),
    sa.Column('menu_board', sa.VARCHAR(), nullable=True),
    sa.Column('reception_branding', sa.VARCHAR(), nullable=True),
    sa.Column('employee_uniform_colors', sqlite.JSON(), nullable=True),
    sa.Column('packaging_style', sa.VARCHAR(), nullable=True),
    sa.Column('business_cards', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['visualization_project_id'], ['visualization_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_versions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('version_number', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=True),
    sa.Column('item_type', sa.VARCHAR(), nullable=False),
    sa.Column('item_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('location_id', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('content', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visualization_images',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('visualization_project_id', sa.VARCHAR(), nullable=False),
    sa.Column('concept_name', sa.VARCHAR(), nullable=False),
    sa.Column('view_type', sa.VARCHAR(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(), nullable=False),
    sa.Column('style', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['visualization_project_id'], ['visualization_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visualization_projects',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('business_type', sa.VARCHAR(), nullable=True),
    sa.Column('business_name', sa.VARCHAR(), nullable=True),
    sa.Column('brand_style', sa.VARCHAR(), nullable=True),
    sa.Column('budget', sa.VARCHAR(), nullable=True),
    sa.Column('target_audience', sa.VARCHAR(), nullable=True),
    sa.Column('store_size', sa.VARCHAR(), nullable=True),
    sa.Column('number_of_floors', sa.INTEGER(), nullable=True),
    sa.Column('preferred_theme', sa.VARCHAR(), nullable=True),
    sa.Column('color_palette', sqlite.JSON(), nullable=True),
    sa.Column('furniture_style', sa.VARCHAR(), nullable=True),
    sa.Column('lighting_style', sa.VARCHAR(), nullable=True),
    sa.Column('outdoor_seating', sa.BOOLEAN(), nullable=True),
    sa.Column('parking_requirement', sa.BOOLEAN(), nullable=True),
    sa.Column('garden', sa.BOOLEAN(), nullable=True),
    sa.Column('drive_through', sa.BOOLEAN(), nullable=True),
    sa.Column('accessibility_features', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_document_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_chroma_id'))

    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_messages_id'))
        batch_op.drop_index(batch_op.f('ix_ai_messages_conversation_id'))

    op.drop_table('ai_messages')
    with op.batch_alter_table('visualization_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visualization_history_project_id'))
        batch_op.drop_index(batch_op.f('ix_visualization_history_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_visualization_history_id'))

    op.drop_table('visualization_history')
    with op.batch_alter_table('startup_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_startup_reports_project_id'))
        batch_op.drop_index(batch_op.f('ix_startup_reports_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_startup_reports_id'))

    op.drop_table('startup_reports')
    with op.batch_alter_table('location_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_analysis_project_id'))
        batch_op.drop_index(batch_op.f('ix_location_analysis_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_location_analysis_id'))

    op.drop_table('location_analysis')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_project_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_id'))

    op.drop_table('knowledge_documents')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_project_id'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_id'))

    op.drop_table('ai_conversations')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_role_id'))

    op.drop_table('user_roles')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_id'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_name'))
        batch_op.drop_index(batch_op.f('ix_permissions_id'))

    op.drop_table('permissions')
    # ### end Alembic commands ###
