"""Restore authentication tables

Revision ID: 9e5f1d781d84
Revises: 83ef0b92cc32
Create Date: 2026-08-15 16:36:36.759250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5f1d781d84'
down_revision: Union[str, Sequence[str], None] = '83ef0b92cc32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otps',
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otps_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_otps_identifier'), ['identifier'], unique=False)

    op.create_table('guest_users',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_converted', sa.Boolean(), nullable=True),
    sa.Column('converted_user_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['converted_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_users_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_users_id'), ['id'], unique=False)

    op.create_table('password_resets',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_resets_token'), ['token'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_resets_user_id'), ['user_id'], unique=False)

    op.create_table('profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_refresh_token'), ['refresh_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('idea_description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('industry', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('business_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('target_users', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tech_preference', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_agent', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('favorite', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pinned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_opened', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_active_tab', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.create_index(batch_op.f('ix_projects_title'), ['title'], unique=False)
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('role')
        batch_op.drop_column('hashed_password')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_projects_title'))
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)
        batch_op.drop_column('is_archived')
        batch_op.drop_column('last_active_tab')
        batch_op.drop_column('last_opened')
        batch_op.drop_column('pinned')
        batch_op.drop_column('favorite')
        batch_op.drop_column('current_agent')
        batch_op.drop_column('progress')
        batch_op.drop_column('tech_preference')
        batch_op.drop_column('target_users')
        batch_op.drop_column('business_type')
        batch_op.drop_column('budget')
        batch_op.drop_column('country')
        batch_op.drop_column('industry')
        batch_op.drop_column('idea_description')
        batch_op.drop_column('title')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_refresh_token'))
        batch_op.drop_index(batch_op.f('ix_sessions_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_profiles_id'))

    op.drop_table('profiles')
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_resets_token'))
        batch_op.drop_index(batch_op.f('ix_password_resets_id'))

    op.drop_table('password_resets')
    with op.batch_alter_table('guest_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_users_id'))
        batch_op.drop_index(batch_op.f('ix_guest_users_device_id'))

    op.drop_table('guest_users')
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otps_identifier'))
        batch_op.drop_index(batch_op.f('ix_otps_id'))

    op.drop_table('otps')
    # ### end Alembic commands ###
